JAMAB_homepage:
  pattern:  /
  defaults: { _controller: JonagueraAulaMentorAlimentosBundle:Default:index }

JAMAB_listar:
  pattern:  /listar
  defaults: { _controller: JonagueraAulaMentorAlimentosBundle:Default:listar }

JAMAB_insertar:
  pattern:  /insertar
  defaults: { _controller: JonagueraAulaMentorAlimentosBundle:Default:insertar }

JAMAB_buscar:
  pattern:  /buscar
  defaults: { _controller: JonagueraAulaMentorAlimentosBundle:Default:buscarPorNombre }

JAMAB_ver:
  pattern:  /ver/{id}
  defaults: { _controller: JonagueraAulaMentorAlimentosBundle:Default:ver }